Test generation tests
prmr/DScribe pull request #8
Opened 2022-04-12 14:06 UTC by lberardelli

Test suite for the TestGeneration package. This involves testing the behaviour of those methods that replace placeholders in a template skeleton (statements with form $placeholder$) with the java statements in a given invocation.

2022-04-20 15:11 UTC, prmr requested changes

2022-04-20 15:11 UTC, prmr commented on src/test/java/ca/mcgill/cs/swevo/dscribe/generation/test/TestTemplateInstantiator.java
> +
extra space

2022-04-20 15:11 UTC, prmr commented on src/test/java/ca/mcgill/cs/swevo/dscribe/generation/test/TestTemplateInstantiator.java
> +		FocalTestPair pair = setup("top.MinimalUsage", "top.TestMinimalUsage", "testdata");
`pair` could be a field initialized in its declaration.

2022-04-22 19:14 UTC, lberardelli commented on src/test/java/ca/mcgill/cs/swevo/dscribe/generation/test/TestTemplateInstantiator.java
> +	{
I was mistaken - it turns out this is used by `TestUnitTestFactory.java`.

2022-04-25 16:57 UTC, merged